HeartRate:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: BloodPressureCuff
  readRate: 5
Sleep:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: SmartWatch
  readRate: 5
BloodPressure:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: BloodPressureCuff
  readRate: 5
Location:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: Phone
  readRate: 5
Busyness:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: Phone
  readRate: 5
Scheduler:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: Calendar
  readRate: 5
Medical:
  dbURI: jdbc:sqlite:src/main/resources/EntityDB.db
  table: MedicalHistory
  readRate: 86400

